version: '2'
services:
    liquibaseinitdatacreator-app:
        image: liquibaseinitdatacreator
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://liquibaseinitdatacreator-mysql:3306/liquibaseinitdatacreator?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    liquibaseinitdatacreator-mysql:
        extends:
            file: mysql.yml
            service: liquibaseinitdatacreator-mysql
